### ISSUE TITLE
allow terse 'enum' syntax (datatype color :red :green :blue) 

### ISSUE THREAD

**Issue by jeske** [samrushing/irken-compiler#41]
The current datatype constructor syntax is a bit overwhelming if you have no parameters to variants, such as:

```scheme
(datatype color
  (:red)
  (:green)
  (:blue))
```

Irken should support dropping the extra () if there are no arguments to the variant. The following would be valid:

```scheme
(datatype color 
   :red 
   :green 
   :blue)

(datatype list 
    :nil 
    (:cons 'a (list 'a)))
```

**Comment by samrushing** [comment]
I tried this, and ran into a problem: ':' is considered a delimiter, so in this...

```scheme
(datatype thing
  :one
  :two
  :three
 )
```

... the reader thinks that `:one` is a type attached to `thing`.
I think the reader needs to stop treating `:` as a delimiter, and instead take apart symbols containing it in a separate pass.

**Comment by jeske** [comment]
Interesting issue. Why does it need to take apart the symbols containing it at all?

**Comment by samrushing** [comment]
Heh, I win the prize for answering something late.  The lexer treats `:` as punctuation, so treating it as a normal character in atoms would require an extra pass over every symbol.  Neither approach is perfect/beautiful/elegant, but treating it as punctuation feels more correct.

The reason I'm here: I've recently added enough smarts to the transform pass that some nifty reflection and other code generation is now possible that was not before.  See ada1d42 for details.
There is now a `make-enum` macro that generates a datatype, some tables, and conversion functions automatically.  It's for generating something closer to a C-style enum, where you can associate explicit values with each name.

Your example above would look like this:

```scheme
(make-enum color
  (red 0)
  (green 1)
  (blue 2)
  )
(printf "green has the value " (int (color->int (color:green))) "\n")
(printf "blue is named " (sym (color->name (color:blue))) "\n")
(printf "1 is named " (sym (color->name (int->color 1))) "\n")
```
